# Generated by Django 4.1 on 2022-08-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_remove_product_image_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, upload_to="products/%Y/%m/%d"),
        ),
        migrations.DeleteModel(
            name="Image",
        ),
    ]
