# Generated by Django 4.1 on 2022-08-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_order_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivered",
            field=models.BooleanField(default=False),
        ),
    ]
